# Generated by Django 4.2.2 on 2023-06-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_courier'),
        ('actions', '0002_alter_mission_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.courier'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
